<?php

/**
 * Implements hook_help()
 */
function iishconference_program_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_program":
			return '<p><strong>About the \'Show Conference Program\' module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_program_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);

	$items[$extraPath . 'program'] = array(
		'title'           => iish_t('Preliminary Program'),
		'page callback'   => 'iishconference_program',
		'access callback' => true,
		'type'            => MENU_NORMAL_ITEM,
		'file'            => 'program.inc.php',
	);

	return $items;
}

/**
 * Implements hook_theme()
 */
function iishconference_program_theme() {
	return array(
		'iishconference_program' => array(
			'template'  => 'iishconference_program',
			'variables' => array(
				'form'                   => null,
				'days'                   => null,
				'date-times'             => null,
				'types'                  => null,
				'program'                => null,
				'paper'                  => null,
				'back-url-query'         => null,
				'highlight'              => null,
				'networkId'              => null,
				'roomId'                 => null,
				'textsearch'             => null,
				'curShowing'             => null,
				'paperDownloadLinkStart' => null,
			),
		),
	);
}