<?php

/**
 * Implements hook_help()
 */
function iishconference_networks_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_networks":
			return '<p><strong>About the module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_networks_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);
	$networkNamePlural = NetworkApi::getNetworkName(false);

	$items[$extraPath . strtolower($networkNamePlural)] = array(
		'title'           => iish_t('Networks', array(), false),
		'page callback'   => 'iishconference_networks',
		'access callback' => true,
		'type'            => MENU_NORMAL_ITEM,
		'file'            => 'networks.inc.php',
	);

	$items[$extraPath . strtolower($networkNamePlural) . '/%iishconference_network'] = array(
		'title callback' => 'iishconference_networks_network_title',
		'title arguments' => array(2),
		'page callback'   => 'iishconference_network_detail',
		'page arguments'  => array(2),
		'access callback' => true,
		'type'            => MENU_CALLBACK,
		'file'            => 'networks.inc.php',
	);

	return $items;
}

/**
 * Implements hook_theme()
 */
function iishconference_networks_theme() {
	return array(
		'conference_networks'       => array(
			'template'  => 'conference_networks',
			'variables' => array(
				'networks' => array(),
			),
		),
		'conference_network_detail' => array(
			'template'  => 'conference_network_detail',
			'variables' => array(
				'network' => null,
			),
		),
	);
}

/**
 * Returns the page title of the network detail page
 *
 * @param NetworkApi|null $network The network the called page shows in detail
 *
 * @return string The title of this page
 */
function iishconference_networks_network_title($network) {
	if (!empty($network)) {
		return $network->getName();
	}

	return NetworkApi::getNetworkName();
}
