<?php
/**
 * @file
 * A block that allows users to see whether they are logged in or not
 */

/**
 * Implements hook_block_info()
 */
function iishconference_userblock_block_info() {
	$blocks['user_block'] = array(
		'info'       => t('User logged in?'),
		'cache'      => DRUPAL_NO_CACHE,
		'status'     => true,
		'region'     => 'header',
		'weight'     => 0,
		'visibility' => BLOCK_VISIBILITY_NOTLISTED,
	);

	return $blocks;
}

/**
 * Implements hook_block_view()
 */
function iishconference_userblock_block_view($delta = '') {
	switch ($delta) {
		case 'user_block':
			$block['subject'] = t('Logged in?');
			$block['content'] = ConferenceMisc::getCleanHTML(iishconference_userblock_block_content(), true);

			return $block;
			break;
	}
}

/**
 * Returns the user block's content
 *
 * @return string The HTML to build the content
 */
function iishconference_userblock_block_content() {
	if (LoggedInUserDetails::isLoggedIn()) {
		return t('Welcome') . ' ' .
		l(LoggedInUserDetails::getUser()->getFullName(), getSetting('pathForMenu') . 'personal-page') . ' | ' .
		l(t('Log out'), getSetting('pathForMenu') . 'logout');
	}
	else {
		return t('You are not logged in. Please !link.',
			array('!link' => l(t('log in'), getSetting('pathForMenu') . 'login')));
	}
}