<?php

/**
 * Implements hook_help()
 */
function iishconference_personalpage_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_personalpage":
			return '<p><strong>About the module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_personalpage_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);

	$items[$extraPath . 'personal-page'] = array(
		'title'           => iish_t('Personal page', array(), false),
		'description'     => 'personal page ...description...',
		'page callback'   => 'conference_personalpage_main',
		'access callback' => true,
		'type'            => MENU_NORMAL_ITEM,
		'file'            => 'personalpage.inc.php',
	);

	$items[$extraPath . 'personal-page/upload-paper/%iishconference_paper'] = array(
		'title'           => iish_t('Upload paper', array(), false),
		'description'     => 'Allows a participant to upload a paper',
		'page callback'   => 'conference_upload_paper',
		'page arguments'  => array(3),
		'access callback' => true,
		'type'            => MENU_CALLBACK,
		'file'            => 'upload_paper.inc.php',
	);

	return $items;
}

/**
 * Implements hook_theme()
 */
function iishconference_personalpage_theme() {
	return array(
		'conference_upload_paper' => array(
			'template'  => 'conference_upload_paper',
			'variables' => array(
				'paper'               => null,
				'paper-download-link' => null,
				'actionUrl'           => null,
				'maxSize'             => null,
				'extensions'          => null,
				'form'                => null,
			),
		),
	);
}
