<?php

/**
 * Implements hook_help
 */
function iishconference_networksparticipantspapers_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_networkparticipants":
			return '<p><strong>About the \'Allows network chairs and crew to download Excel files with participant and paper info for a specified network\' module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu
 */
function iishconference_networksparticipantspapers_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);
	$networkNameSingular = NetworkApi::getNetworkName();
	$networkNamePlural = NetworkApi::getNetworkName(false);

	$items[$extraPath . strtolower($networkNamePlural) . 'participantspapers'] = array(
		'title'           => iish_t('Networks and their Participants (incl. Papers)', array(), false),
		'page callback'   => 'iishconference_networksparticipantspapers_main',
		'access callback' => true,
		'type'            => MENU_NORMAL_ITEM,
		'file'            => 'networksparticipantspapers.inc.php',
	);

	$items[$extraPath . strtolower($networkNamePlural) . 'participantspapers/%iishconference_network'] = array(
		'title'           => iish_t('Network and its Participants (incl. Papers)', array(), false),
		'page callback'   => 'iishconference_networksparticipantspapers_detail',
		'page arguments'  => array(2),
		'access callback' => true,
		'type'            => MENU_CALLBACK,
		'file'            => 'networksparticipantspapers.inc.php',
	);

	return $items;
}
