<?php

/**
 * Implements hook_help()
 */
function iishconference_preregistration_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_preregistration":
			return '<p><strong>About the \'Pre-registration\' module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_preregistration_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);

	$items[$extraPath . 'pre-registration'] = array(
		'title'           => 'Pre-registration for the ' . CachedConferenceApi::getEventDate()->getLongCodeAndYear() . ' conference',
		'description'     => 'Pre-registration ...description...',
		'page callback'   => 'drupal_get_form',
		'page arguments'  => array('preregister_form'),
		'access callback' => true,
		'type'            => MENU_NORMAL_ITEM,
		'file'            => 'preregister.inc.php',
	);

	return $items;
}
