<?php

/**
 * Implements hook_help()
 */
function iishconference_electionadvisory_help($path, $arg) {
	switch ($path) {
		case "admin/help#iishconference_electionadvisory":
			return '<p><strong>About the module</strong><br><br>...</p>';
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_electionadvisory_menu() {
	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);

	$items[$extraPath . 'election-advisory-board'] = array(
		'title'           => iish_t('Election \'Advisory board\'', array(), false),
		'page callback'   => 'iishconference_electionadvisory_main',
		'access callback' => true,
		'type'            => MENU_NORMAL_ITEM,
		'file'            => 'iishconference_electionadvisory_main.inc.php',
	);

	return $items;
}