<?php

/**
 * Implements hook_help()
 */
function iishconference_changepassword_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_changepassword":
			return '<p><strong>About the module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_changepassword_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);

	$items[$extraPath . 'change-password'] = array(
		'title'           => iish_t('Change password', array(), false),
		'description'     => 'change password page ...description...',
		'page callback'   => 'drupal_get_form',
		'page arguments'  => array('conference_changepassword_form'),
		'access callback' => true,
		'type'            => MENU_CALLBACK,
		'file'            => 'changepassword.inc.php',
	);

	return $items;
}
