<?php

/**
 * Implements hook_help()
 */
function iishconference_programme_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_programme":
			return '<p><strong>About the \'Show Conference Programme\' module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_programme_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);

	$title = SettingsApi::getSetting(SettingsApi::ONLINE_PROGRAM_HEADER);

	$items[$extraPath . 'programme'] = array(
		'title'           => $title,
		'page callback'   => 'iishconference_programme',
		'access callback' => true,
		'type'            => MENU_NORMAL_ITEM,
		'file'            => 'programme.inc.php',
	);
	//'title'           => iish_t('Programme', array(), false),

	return $items;
}

/**
 * Implements hook_theme()
 */
function iishconference_programme_theme() {
	return array(
		'iishconference_programme' => array(
			'template'  => 'iishconference_programme',
			'variables' => array(
				'eventDate'              => null,
				'form'                   => null,
				'days'                   => null,
				'date-times'             => null,
				'types'                  => null,
				'programme'              => null,
				'paper'                  => null,
				'back-url-query'         => null,
				'highlight'              => null,
				'networkId'              => null,
				'roomId'                 => null,
				'textsearch'             => null,
				'curShowing'             => null,
				'downloadPaperIsOpen'    => null,
				'paperDownloadLinkStart' => null,
			),
		),
	);
}
