<?php

/**
 * Implements hook_help()
 */
function iishconference_networksforchairs_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_networksforchairs":
			return '<p><strong>About the \'Show Network, Sessions & Participants to Network Chairs\' module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_networksforchairs_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);

	$items[$extraPath . 'networksforchairs'] = array(
		'title'           => 'Networks, Sessions & Participants',
		'description'     => 'Networks, Sessions & Participants ...description...',
		'page callback'   => 'iishconference_networksforchairs_main',
		'access callback' => true,
		'type'            => MENU_NORMAL_ITEM,
		'file'            => 'networksforchairs.inc.php',
	);

	$items[$extraPath . 'networksforchairs/%'] = array(
		'title'           => 'Networks, Sessions & Participants',
		'description'     => 'Networks, Sessions & Participants ...description...',
		'page callback'   => 'iishconference_networksforchairs_sessions',
		'page arguments'  => array(2),
		'access callback' => true,
		'type'            => MENU_CALLBACK,
		'file'            => 'networksforchairs.inc.php',
	);

	$items[$extraPath . 'networksforchairs/%/%'] = array(
		'title'           => 'Networks, Sessions & Participants',
		'description'     => 'Networks, Sessions & Participants ...description...',
		'page callback'   => 'iishconference_networksforchairs_papers',
		'page arguments'  => array(2, 3),
		'access callback' => true,
		'type'            => MENU_CALLBACK,
		'file'            => 'networksforchairs.inc.php',
	);

	return $items;
}
