<?php

/**
 * Implements hook_help()
 */
function iishconference_networkvolunteers_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_networkvolunteers":
			return '<p><strong>About the \'Show Networks and their Volunteers\' module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_networkvolunteers_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);

	$items[$extraPath . 'networkvolunteers'] = array(
		'title'           => 'Networks & Volunteers',
		'description'     => 'Networks & their volunteers ...description...',
		'page callback'   => 'iishconference_networkvolunteers_main',
		'access callback' => true,
		'type'            => MENU_NORMAL_ITEM,
		'file'            => 'networkvolunteers.inc.php',
	);

	$items[$extraPath . 'networkvolunteers/%iishconference_network'] = array(
		'title'           => 'Network and its volunteers',
		'description'     => 'Network and its volunteers ...description...',
		'page callback'   => 'iishconference_networkvolunteers_detail',
		'page arguments'  => array(2),
		'access callback' => true,
		'type'            => MENU_CALLBACK,
		'file'            => 'networkvolunteers.inc.php',
	);

	return $items;
}
