<?php

/**
 * Implements hook_help()
 */
function iishconference_logout_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_logout":
			return '<p><strong>About the module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_logout_menu() {
	$items = array();

	$extraPath = getSetting('pathForMenu');

	$items[$extraPath . 'logout'] = array(
		'title'           => 'Logout',
		'description'     => 'logout page ...description...',
		'page callback'   => 'drupal_get_form',
		'page arguments'  => array('conference_logout_form'),
		'access callback' => true,
		'type'            => MENU_NORMAL_ITEM,
		'file'            => 'logout.inc.php',
	);

	return $items;
}
