<?php

/**
 * Implements hook_help()
 */
function iishconference_proposednetworkparticipants_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_proposednetworkparticipants":
			return '<p><strong>About the \'Show Participants and their proposed network\' module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_proposednetworkparticipants_menu() {
	$items = array();

	$extraPath = getSetting('pathForMenu');

	$items[$extraPath . 'proposednetworkparticipants'] = array(
		'title'           => 'Participants and their proposed network',
		'description'     => 'Networks & their participants ...description...',
		'page callback'   => 'iishconference_proposednetworkparticipants_main',
		'type'            => MENU_NORMAL_ITEM,
		'access callback' => true,
		'file'            => 'proposednetworkparticipants.inc.php',
	);

	$items[$extraPath . 'proposednetworkparticipants/%iishconference_network'] = array(
		'title'           => 'Participants and their proposed network',
		'description'     => 'Networks & their participants ...description...',
		'page callback'   => 'iishconference_proposednetworkparticipants_detail',
		'page arguments'  => array(2),
		'type'            => MENU_NORMAL_ITEM,
		'access callback' => true,
		'file'            => 'proposednetworkparticipants.inc.php',
	);

	return $items;
}
