<?php

/**
 * Implements hook_help()
 */
function iishconference_proposednetworkparticipants_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_proposednetworkparticipants":
			return '<p><strong>About the \'Show Participants and their proposed network\' module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_proposednetworkparticipants_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);
	$networkNameSingular = NetworkApi::getNetworkName();

	$items[$extraPath . 'proposed' . strtolower($networkNameSingular) . 'participants'] = array(
		'title'           => iish_t('Participants and their proposed networks', array(), false),
		'page callback'   => 'iishconference_proposednetworkparticipants_main',
		'type'            => MENU_NORMAL_ITEM,
		'access callback' => true,
		'file'            => 'proposednetworkparticipants.inc.php',
	);

	$items[$extraPath . 'proposed' . strtolower($networkNameSingular) . 'participants/%iishconference_network'] = array(
		'title'           => iish_t('Participants and their proposed networks', array(), false),
		'page callback'   => 'iishconference_proposednetworkparticipants_detail',
		'page arguments'  => array(2),
		'type'            => MENU_NORMAL_ITEM,
		'access callback' => true,
		'file'            => 'proposednetworkparticipants.inc.php',
	);

	return $items;
}
