<?php

/**
 * Implements hook_help()
 */
function iishconference_lostpassword_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_lostpassword":
			return '<p><strong>About the module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_lostpassword_menu() {
	$items = array();

	$extraPath = getSetting('pathForMenu');

	$items[$extraPath . 'lost-password'] = array(
		'title'           => 'Lost password',
		'description'     => 'lost password page ...description...',
		'page callback'   => 'drupal_get_form',
		'page arguments'  => array('conference_lostpassword_form'),
		'access callback' => true,
		'type'            => MENU_CALLBACK,
		'file'            => 'lostpassword.inc.php',
	);

	return $items;
}
