<?php

/**
 * Implements hook_help()
 */
function iishconference_confirmlostpassword_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_confirmlostpassword":
			return '<p><strong>About the module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function iishconference_confirmlostpassword_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);

	$items[$extraPath . 'confirm-lost-password'] = array(
		'title'           => 'Confirm lost password',
		'description'     => 'confirm lost password page ...description...',
		'page callback'   => 'drupal_get_form',
		'page arguments'  => array('conference_confirmlostpassword_form'),
		'access callback' => true,
		'type'            => MENU_CALLBACK,
		'file'            => 'confirmlostpassword.inc.php',
	);

	return $items;
}
