<?php

function iishconference_login_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_login":
			return '<p><strong>About the module</strong><br><br>...</p>';
			break;
	}
}

function iishconference_login_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);

	$items[$extraPath . 'login'] = array(
		'title'           => iish_t('Login', array(), false),
		'description'     => 'login page ...description...',
		'page callback'   => 'drupal_get_form',
		'page arguments'  => array('conference_login_form'),
		'access callback' => true,
		'type'            => MENU_NORMAL_ITEM,
		'file'            => 'login.inc.php',
	);

	return $items;
}