<?php


function iishconference_login_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_login":
			return '<p><strong>About the module</strong><br><br>...</p>';
			break;
	}
}

function iishconference_login_menu() {
	$items = array();

	$extraPath = getSetting('pathForMenu');

	$items[$extraPath . 'login'] = array(
		'title'           => 'Login',
		'description'     => 'login page ...description...',
		'page callback'   => 'drupal_get_form',
		'page arguments'  => array('conference_login_form'),
		'access callback' => true,
		'file'            => 'login.inc.php',
	);

	return $items;
}