<?php

/**
 * Implements hook_help
 */
function iishconference_networkindividualpapersxls_help($path, $arg) {
	switch ($path) {
		// Module help for the block module
		case "admin/help#iishconference_networkindividualpapersxls":
			return '<p><strong>About the \'Allows network chairs to download an Excel file with participants and individual paper proposals\' module</strong><br><br>...</p>';
			break;
	}
}

/**
 * Implements hook_menu
 */
function iishconference_networkindividualpapersxls_menu() {
	$items = array();

	$extraPath = SettingsApi::getSetting(SettingsApi::PATH_FOR_MENU);
	$networkNameSingular = NetworkApi::getNetworkName();
	$networkNamePlural = NetworkApi::getNetworkName(false);

	$items[$extraPath . strtolower($networkNameSingular) . 'individualpapersxls'] = array(
		'title'           => iish_t('Participants and their individual paper proposals', array(), false),
		'page callback'   => 'iishconference_networkindividualpapersxls_main',
		'access callback' => true,
		'type'            => MENU_NORMAL_ITEM,
		'file'            => 'networkindividualpapersxls.inc.php',
	);

	$items[$extraPath . strtolower($networkNameSingular) . 'individualpapersxls/%iishconference_network'] = array(
		'title'           => iish_t('Participants and their individual paper proposals', array(), false),
		'page callback'   => 'iishconference_networkindividualpapersxls_detail',
		'page arguments'  => array(2),
		'access callback' => true,
		'type'            => MENU_CALLBACK,
		'file'            => 'networkindividualpapersxls.inc.php',
	);

	return $items;
}
